name: kyohei
version: 1.0.0
description: APM project for kyohei
author: Kyohei Ozawa
dependencies:
  apm:
    - mattpocock/skills/skills/productivity/grill-me
    - mizchi/skills/meta/empirical-prompt-tuning
    - git: refoundai/lenny-skills
      skills:
        - running-decision-processes
    - git: zawa-kyo/skills
      skills:
        - dev/review-essential-code
        - dev/suggest-commit-messages
        - writing/revise-japanese-writing
        - writing/revise-english-writing
        - writing/edit-existing-document
  mcp: []
includes: auto
scripts: {}
