#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dotfiles_dir="$(cd "$script_dir/.." && pwd)"
source "$script_dir/../libexec/log.sh"
source "$script_dir/../libexec/path.sh"

global_commands_dir="$dotfiles_dir/bin"
local_bin_dir="${DIR_LOCAL_BIN:-$HOME/.local/bin}"
mise_tasks_dir="${DIR_MISE_TASKS:-$HOME/.config/mise/tasks}"
generated_marker="# Generated by tasks/sync-global-commands.sh. Do not edit."
legacy_generated_marker="# Generated by scripts/local/sync-global-commands.sh. Do not edit."

# Create a directory when it does not exist.
ensure_dir() {
  local dir="$1"

  if [ -d "$dir" ]; then
    return 0
  fi

  mkdir -p "$dir"
  info "Created directory: $dir"
}

# Link a command without replacing user-owned files.
install_symlink() {
  local source_path="$1"
  local target_path="$2"

  if [ -L "$target_path" ]; then
    if [ "$(readlink "$target_path")" = "$source_path" ]; then
      return 0
    fi
    if ! symlink_points_within_dir "$target_path" "$dotfiles_dir"; then
      warn "$target_path points outside the dotfiles repository. Skipping."
      return 0
    fi
    rm "$target_path"
    info "Removed existing symlink: $target_path"
  elif [ -e "$target_path" ]; then
    warn "$target_path exists and is not a symlink. Skipping."
    return 0
  fi

  ln -s "$source_path" "$target_path"
  info "Linked: $target_path"
}

# Return success when the file is a wrapper generated by this repository.
is_generated_wrapper() {
  local path="$1"

  [ -f "$path" ] || return 1
  grep -Fqx "$generated_marker" "$path" || grep -Fqx "$legacy_generated_marker" "$path"
}

# Remove command links whose managed source no longer exists.
remove_stale_global_commands() {
  local -a expected_names=("$@")
  local file
  local keep
  local link_target
  local name

  [ -d "$local_bin_dir" ] || return 0

  for file in "$local_bin_dir"/*; do
    [ -L "$file" ] || continue
    link_target="$(readlink "$file")"
    case "$link_target" in
    "$global_commands_dir"/* | "$dotfiles_dir/scripts/global"/*) ;;
    *) continue ;;
    esac

    name="$(basename "$file")"
    keep=false
    for expected in "${expected_names[@]}"; do
      if [ "$name" = "$expected" ]; then
        keep=true
        break
      fi
    done

    if [ "$keep" = false ]; then
      rm -f "$file"
      info "Removed stale global command link: $file"
    fi
  done
}

# Remove only mise wrappers created by the former publication flow.
remove_generated_mise_tasks() {
  local legacy_tasks_dir="$dotfiles_dir/.cache/mise/tasks"
  local file
  local link_target

  if [ -d "$mise_tasks_dir" ]; then
    for file in "$mise_tasks_dir"/*; do
      [ -e "$file" ] || [ -L "$file" ] || continue

      if is_generated_wrapper "$file"; then
        rm -f "$file"
        info "Removed generated mise wrapper: $file"
        continue
      fi

      [ -L "$file" ] || continue
      link_target="$(readlink "$file")"
      case "$link_target" in
      "$legacy_tasks_dir"/*)
        rm -f "$file"
        info "Removed legacy mise task link: $file"
        ;;
      esac
    done
  fi

  [ -d "$legacy_tasks_dir" ] || return 0
  for file in "$legacy_tasks_dir"/*; do
    [ -e "$file" ] || continue
    is_generated_wrapper "$file" || continue
    rm -f "$file"
    info "Removed legacy generated wrapper: $file"
  done
}

# Publish standalone commands to PATH and remove former mise wrappers.
main() {
  local command_path
  local command_name
  local command_basename
  local -a command_names=()

  ensure_dir "$local_bin_dir"

  for command_path in "$global_commands_dir"/*; do
    [ -f "$command_path" ] || continue

    command_basename="$(basename "$command_path")"
    case "$command_basename" in
    *.sh) command_name="${command_basename%.sh}" ;;
    *.bash) command_name="${command_basename%.bash}" ;;
    *) command_name="$command_basename" ;;
    esac

    command_names+=("$command_name")
    install_symlink "$command_path" "$local_bin_dir/$command_name"
  done

  remove_stale_global_commands "${command_names[@]}"
  remove_generated_mise_tasks
}

main "$@"
