package bootstrap_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

const miseBootstrapMigration = "setup/migrations/migrate-to-mise-bootstrap.sh"

// TestLegacyAPMDataMigration verifies generated modules survive the layout change.
func TestLegacyAPMDataMigration(t *testing.T) {
	repo := repositoryRoot(t)
	fixtureRepo := t.TempDir()
	home := t.TempDir()
	legacySource := filepath.Join(fixtureRepo, "packages", "apm")
	currentSource := filepath.Join(fixtureRepo, "dotfiles", "ai", "apm")

	mustWriteFile(t, filepath.Join(currentSource, "apm.yml"), "dependencies: []\n", 0o644)
	mustWriteFile(t, filepath.Join(legacySource, "apm_modules", "example", "data"), "cached\n", 0o644)
	mustSymlink(t, legacySource, filepath.Join(home, ".apm"))

	runCommand(t, repo, migrationEnvironment(home), "bash", filepath.Join(repo, miseBootstrapMigration), fixtureRepo)

	assertFileContent(t, filepath.Join(home, ".apm", "apm_modules", "example", "data"), "cached\n")
	if _, err := os.Lstat(filepath.Join(legacySource, "apm_modules")); !os.IsNotExist(err) {
		t.Fatalf("legacy APM modules remain in the repository: %v", err)
	}
}

// TestPreviousAPMSourceMigration verifies links from the former config layout remain migratable.
func TestPreviousAPMSourceMigration(t *testing.T) {
	repo := repositoryRoot(t)
	fixtureRepo := t.TempDir()
	home := t.TempDir()
	currentSource := filepath.Join(fixtureRepo, "dotfiles", "ai", "apm")
	previousSource := filepath.Join(fixtureRepo, "config", "ai", "apm")

	mustWriteFile(t, filepath.Join(currentSource, "apm.yml"), "dependencies: []\n", 0o644)
	mustWriteFile(t, filepath.Join(previousSource, "apm_modules", "example", "data"), "cached\n", 0o644)
	mustSymlink(t, previousSource, filepath.Join(home, ".apm"))

	runCommand(t, repo, migrationEnvironment(home), "bash", filepath.Join(repo, miseBootstrapMigration), fixtureRepo)

	assertFileContent(t, filepath.Join(home, ".apm", "apm_modules", "example", "data"), "cached\n")
}

// TestLegacyAPMMigrationRejectsForeignLink verifies migration requires known ownership.
func TestLegacyAPMMigrationRejectsForeignLink(t *testing.T) {
	repo := repositoryRoot(t)
	fixtureRepo := t.TempDir()
	home := t.TempDir()
	foreignSource := t.TempDir()
	target := filepath.Join(home, ".apm")

	mustWriteFile(t, filepath.Join(fixtureRepo, "dotfiles", "ai", "apm", "apm.yml"), "dependencies: []\n", 0o644)
	mustSymlink(t, foreignSource, target)

	command := exec.Command("bash", filepath.Join(repo, miseBootstrapMigration), fixtureRepo)
	command.Dir = repo
	command.Env = replaceEnvironment(os.Environ(), migrationEnvironment(home))
	if output, err := command.CombinedOutput(); err == nil {
		t.Fatalf("migration unexpectedly replaced an unmanaged APM link:\n%s", output)
	}
	assertLink(t, target, foreignSource)
}

// TestLegacyCommandWrapperCleanup verifies migration removes only generated wrappers.
func TestLegacyCommandWrapperCleanup(t *testing.T) {
	repo := repositoryRoot(t)
	fixtureRepo := t.TempDir()
	home := t.TempDir()
	tasksDir := filepath.Join(home, ".config", "mise", "tasks")

	mustWriteFile(t, filepath.Join(fixtureRepo, "dotfiles", "ai", "apm", "apm.yml"), "dependencies: []\n", 0o644)
	mustWriteFile(t, filepath.Join(tasksDir, "generated"), "#!/usr/bin/env bash\n# Generated by tasks/sync-global-commands.sh. Do not edit.\n", 0o755)
	mustWriteFile(t, filepath.Join(tasksDir, "unrelated"), "#!/usr/bin/env bash\n# user-owned\n", 0o755)

	runCommand(t, repo, migrationEnvironment(home), "bash", filepath.Join(repo, miseBootstrapMigration), fixtureRepo)

	if _, err := os.Lstat(filepath.Join(tasksDir, "generated")); !os.IsNotExist(err) {
		t.Fatalf("generated wrapper was not removed: %v", err)
	}
	assertFileContent(t, filepath.Join(tasksDir, "unrelated"), "#!/usr/bin/env bash\n# user-owned\n")
}

// TestBunDataMigration verifies generated modules survive both earlier layouts.
func TestBunDataMigration(t *testing.T) {
	for _, sourceKind := range []string{"previous", "legacy"} {
		t.Run(sourceKind, func(t *testing.T) {
			repo := repositoryRoot(t)
			source := filepath.Join(t.TempDir(), "bun-source")
			oldSource := filepath.Join(t.TempDir(), "bun-"+sourceKind)
			unusedSource := filepath.Join(t.TempDir(), "unused")
			globalDir := filepath.Join(t.TempDir(), "global")
			globalBin := filepath.Join(t.TempDir(), "bin")
			fakeBin := t.TempDir()

			mustWriteFile(t, filepath.Join(source, "package.json"), "{\"dependencies\":{}}\n", 0o644)
			mustWriteFile(t, filepath.Join(source, "bun.lock"), "lock\n", 0o644)
			mustWriteFile(t, filepath.Join(source, "bunfig.toml"), "[install]\n", 0o644)
			mustWriteFile(t, filepath.Join(oldSource, "node_modules", ".bin", "example"), "#!/usr/bin/env bash\n", 0o755)
			mustWriteFile(t, filepath.Join(fakeBin, "bun"), "#!/usr/bin/env bash\nexit 0\n", 0o755)
			mustSymlink(t, oldSource, globalDir)

			previousSource := unusedSource
			legacySource := oldSource
			if sourceKind == "previous" {
				previousSource = oldSource
				legacySource = unusedSource
			}
			runCommand(t, repo, map[string]string{
				"DIR_BUN_SOURCE":          source,
				"DIR_BUN_PREVIOUS_SOURCE": previousSource,
				"DIR_BUN_LEGACY_SOURCE":   legacySource,
				"DIR_BUN_GLOBAL":          globalDir,
				"DIR_BUN_BIN":             globalBin,
				"PATH":                    fakeBin + string(os.PathListSeparator) + os.Getenv("PATH"),
			}, "bash", filepath.Join(repo, "setup", "install-bun.sh"))

			assertFileContent(t, filepath.Join(globalDir, "node_modules", ".bin", "example"), "#!/usr/bin/env bash\n")
			assertLinkResolves(t, filepath.Join(globalBin, "example"), filepath.Join(globalDir, "node_modules", ".bin", "example"))
			if _, err := os.Lstat(filepath.Join(oldSource, "node_modules")); !os.IsNotExist(err) {
				t.Fatalf("old Bun modules remain in the repository: %v", err)
			}
		})
	}
}

// migrationEnvironment isolates every user-controlled migration path.
func migrationEnvironment(home string) map[string]string {
	return map[string]string{
		"HOME":                   home,
		"DIR_MISE_TASKS":         filepath.Join(home, ".config", "mise", "tasks"),
		"DIR_CLAUDE_CODE_SKILLS": filepath.Join(home, ".claude", "skills"),
		"DIR_CODEX_SKILLS":       filepath.Join(home, ".codex", "skills"),
		"DIR_COPILOT_SKILLS":     filepath.Join(home, ".copilot", "skills"),
		"DIR_GEMINI_CLI_SKILLS":  filepath.Join(home, ".gemini", "skills"),
		"DIR_SKILLS":             filepath.Join(home, ".local", "share", "dotfiles", "skills"),
		"DIR_APM_MODULES":        filepath.Join(home, ".apm", "apm_modules"),
	}
}

// assertLinkResolves compares canonical targets across platform path aliases.
func assertLinkResolves(t *testing.T, path string, expected string) {
	t.Helper()
	actualTarget, err := filepath.EvalSymlinks(path)
	if err != nil {
		t.Fatalf("resolve symlink %s: %v", path, err)
	}
	expectedTarget, err := filepath.EvalSymlinks(expected)
	if err != nil {
		t.Fatalf("resolve expected path %s: %v", expected, err)
	}
	if actualTarget != expectedTarget {
		t.Fatalf("symlink %s resolves to %s, want %s", path, actualTarget, expectedTarget)
	}
}

// runCommand runs a repository helper with controlled environment variables.
func runCommand(t *testing.T, workingDirectory string, env map[string]string, name string, args ...string) string {
	t.Helper()
	command := exec.Command(name, args...)
	command.Dir = workingDirectory
	command.Env = replaceEnvironment(os.Environ(), env)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("%s failed: %v\n%s", name, err, output)
	}
	return string(output)
}
