[tools]
bun = "1.3.10"
deno = "2.7.1"
flutter = "3.41.2-stable"
go = "1.26.0"
java = "21.0.2"
maestro = "cli-2.4.0"
node = "24.14.0"
python = "3.14.3"
ruby = "3.4.8"
rust = "1.93.1"
uv = "0.10.7"
zellij = "0.43.1"
