#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dotfiles_dir="$(cd "$script_dir/../.." && pwd)"
source "$script_dir/../utils/log.sh"

global_commands_dir="$dotfiles_dir/scripts/global"
generated_tasks_dir="$dotfiles_dir/.cache/mise/tasks"
local_bin_dir="${DIR_LOCAL_BIN:-$HOME/.local/bin}"
mise_tasks_dir="${DIR_MISE_TASKS:-$HOME/.config/mise/tasks}"

ensure_dir() {
  local dir="$1"

  if [ -d "$dir" ]; then
    return 0
  fi

  mkdir -p "$dir"
  info "Created directory: $dir"
}

install_symlink() {
  local source_path="$1"
  local target_path="$2"

  if [ -L "$target_path" ]; then
    if [ "$(readlink "$target_path")" = "$source_path" ]; then
      return 0
    fi
    rm "$target_path"
    info "Removed existing symlink: $target_path"
  elif [ -e "$target_path" ]; then
    warn "$target_path exists and is not a symlink. Skipping."
    return 0
  fi

  ln -s "$source_path" "$target_path"
  info "Linked: $target_path"
}

write_wrapper_if_changed() {
  local command_name="$1"
  local description="$2"
  local target_path="$generated_tasks_dir/$command_name"
  local tmpfile

  tmpfile="$(mktemp)"
  cat >"$tmpfile" <<EOF
#!/usr/bin/env bash
# Generated by scripts/local/sync-global-commands.sh. Do not edit.
#MISE description="$description"
if [ -n "\${MISE_ORIGINAL_CWD:-}" ]; then
  cd -- "\$MISE_ORIGINAL_CWD"
fi
exec $command_name "\$@"
EOF

  if [ -f "$target_path" ] && cmp -s "$tmpfile" "$target_path"; then
    rm -f "$tmpfile"
    return 0
  fi

  mv "$tmpfile" "$target_path"
  chmod +x "$target_path"
  info "Generated mise wrapper: $target_path"
}

remove_stale_generated_wrappers() {
  local -a expected_names=("$@")
  local file
  local name
  local keep

  [ -d "$generated_tasks_dir" ] || return 0

  for file in "$generated_tasks_dir"/*; do
    [ -e "$file" ] || continue
    name="$(basename "$file")"
    keep=false
    for expected in "${expected_names[@]}"; do
      if [ "$name" = "$expected" ]; then
        keep=true
        break
      fi
    done
    if [ "$keep" = false ]; then
      rm -f "$file"
      info "Removed stale generated wrapper: $file"
    fi
  done
}

remove_stale_task_links() {
  local -a expected_names=("$@")
  local file
  local link_target
  local name
  local keep

  [ -d "$mise_tasks_dir" ] || return 0

  for file in "$mise_tasks_dir"/*; do
    [ -L "$file" ] || continue
    link_target="$(readlink "$file")"
    case "$link_target" in
    "$generated_tasks_dir"/*) ;;
    *) continue ;;
    esac

    name="$(basename "$file")"
    keep=false
    for expected in "${expected_names[@]}"; do
      if [ "$name" = "$expected" ]; then
        keep=true
        break
      fi
    done
    if [ "$keep" = false ]; then
      rm -f "$file"
      info "Removed stale mise task link: $file"
    fi
  done
}

main() {
  local command_path
  local command_name
  local command_basename
  local description
  local -a command_names=()

  ensure_dir "$local_bin_dir"
  ensure_dir "$generated_tasks_dir"
  ensure_dir "$mise_tasks_dir"

  for command_path in "$global_commands_dir"/*; do
    [ -f "$command_path" ] || continue

    command_basename="$(basename "$command_path")"
    case "$command_basename" in
    *.sh) command_name="${command_basename%.sh}" ;;
    *.bash) command_name="${command_basename%.bash}" ;;
    *) command_name="$command_basename" ;;
    esac
    command_names+=("$command_name")

    install_symlink "$command_path" "$local_bin_dir/$command_name"

    description="$(sed -n 's/^# MISE_DESCRIPTION: //p' "$command_path" | head -n 1)"
    if [ -z "$description" ]; then
      warn "Missing MISE_DESCRIPTION in $command_path. Skipping mise wrapper."
      continue
    fi

    write_wrapper_if_changed "$command_name" "$description"
    install_symlink "$generated_tasks_dir/$command_name" "$mise_tasks_dir/$command_name"
  done

  remove_stale_generated_wrappers "${command_names[@]}"
  remove_stale_task_links "${command_names[@]}"
}

main "$@"
